import Link from "next/link"

export default function ArtistDisclaimerPage() {
  return (
    <div className="container mx-auto px-4 py-12 max-w-4xl">
      <div className="text-center mb-12">
        <h1 className="text-4xl font-bold mb-4">Artist Disclaimer</h1>
        <p className="text-gray-600">Last updated: {new Date().toLocaleDateString()}</p>
      </div>

      <div className="prose prose-amber max-w-none">
        <p>
          This Artist Disclaimer ("Disclaimer") outlines important information for artists who upload and share their
          work on the Redeemed Creative Arts platform. By uploading artwork to the Platform, you acknowledge and agree
          to the terms of this Disclaimer.
        </p>

        <h2>1. Intellectual Property Rights</h2>
        <h3>1.1 Ownership</h3>
        <p>
          You retain ownership of all intellectual property rights in your artwork. By uploading your artwork to the
          Platform, you grant us a non-exclusive, worldwide, royalty-free license to use, reproduce, modify, adapt,
          publish, translate, create derivative works from, distribute, and display such artwork in connection with
          providing and promoting the Platform.
        </p>

        <h3>1.2 Original Work</h3>
        <p>You represent and warrant that:</p>
        <ul>
          <li>Your artwork is your original creation or you have all necessary rights to upload it</li>
          <li>Your artwork does not infringe upon the intellectual property rights of any third party</li>
          <li>Your artwork does not violate any laws or regulations</li>
          <li>Your artwork is not created using AI generation tools (see Section 3)</li>
        </ul>

        <h2>2. Content Guidelines</h2>
        <p>
          As a faith-based platform, we expect all artwork to align with Christian values. Artwork should not contain:
        </p>
        <ul>
          <li>Explicit sexual content or nudity</li>
          <li>Graphic violence or gore</li>
          <li>Hate speech or discriminatory content</li>
          <li>Blasphemous or sacrilegious content</li>
          <li>Content that promotes illegal activities</li>
        </ul>
        <p>
          We reserve the right to remove any artwork that violates these guidelines or that we determine, in our sole
          discretion, is inappropriate for our Platform.
        </p>

        <h2>3. No AI Art Policy</h2>
        <p>
          Redeemed Creative Arts values authentic human creativity. We do not allow artwork created primarily through AI
          generation tools. By uploading artwork, you confirm that:
        </p>
        <ul>
          <li>Your artwork is created by you, not generated by AI tools</li>
          <li>
            While digital tools and software may be used in your creative process, the artistic expression and creative
            direction are your own
          </li>
          <li>
            If you use AI as a minor component in your creative process, it must be disclosed in the artwork description
          </li>
        </ul>
        <p>Violation of this policy may result in removal of the artwork and potential suspension of your account.</p>

        <h2>4. Sales and Commissions</h2>
        <h3>4.1 Platform Fees</h3>
        <p>
          When your artwork sells through the Platform, a platform fee will be deducted from the sale price. The current
          fee structure is:
        </p>
        <ul>
          <li>Free Tier: 15% of sale price</li>
          <li>Tier 1: 10% of sale price</li>
          <li>Tier 2: 8% of sale price</li>
        </ul>
        <p>These fees help maintain and improve the Platform for all users.</p>

        <h3>4.2 Payment Processing</h3>
        <p>
          Payments for sold artwork will be processed according to our payment schedule and transferred to your
          connected payment account. You are responsible for providing accurate payment information and for any taxes
          associated with your sales.
        </p>

        <h2>5. Representation and Promotion</h2>
        <p>
          We may feature your artwork in promotional materials, social media, and other marketing efforts to promote the
          Platform and your work. This may include using your artwork in:
        </p>
        <ul>
          <li>Featured artwork sections</li>
          <li>Social media posts</li>
          <li>Email newsletters</li>
          <li>Platform advertisements</li>
        </ul>
        <p>If you do not want your artwork used for promotional purposes, please contact us.</p>

        <h2>6. Dispute Resolution</h2>
        <p>
          If a dispute arises regarding your artwork (e.g., intellectual property claims, content violations), we will:
        </p>
        <ul>
          <li>Notify you of the dispute</li>
          <li>Temporarily remove the artwork pending investigation if necessary</li>
          <li>Provide you with an opportunity to respond</li>
          <li>Make a determination based on available information</li>
        </ul>
        <p>Our decisions regarding disputes are final, though we strive to be fair and transparent in our process.</p>

        <h2>7. Limitation of Liability</h2>
        <p>
          While we take reasonable measures to protect your artwork on our Platform, we cannot guarantee absolute
          security. We are not liable for:
        </p>
        <ul>
          <li>Unauthorized copying or use of your artwork by third parties</li>
          <li>Technical issues that may affect the display or availability of your artwork</li>
          <li>Disputes between you and buyers or other users</li>
        </ul>

        <h2>8. Changes to this Disclaimer</h2>
        <p>
          We may modify this Disclaimer at any time. If we make changes, we will provide notice by updating the date at
          the top of this Disclaimer and by maintaining a current version on the Platform. Your continued use of the
          Platform after any such changes constitutes your acceptance of the new Disclaimer.
        </p>

        <h2>9. Contact Information</h2>
        <p>If you have any questions about this Disclaimer, please contact us at:</p>
        <p>
          Email: artists@redeemedcreativearts.com
          <br />
          Address: 123 Faith Avenue, Creative City, CA 12345
        </p>
      </div>

      <div className="mt-12 text-center">
        <Link href="/terms" className="text-amber-600 hover:underline">
          View Terms of Service
        </Link>
        {" | "}
        <Link href="/privacy" className="text-amber-600 hover:underline">
          View Privacy Policy
        </Link>
        {" | "}
        <Link href="/helper-agreement" className="text-amber-600 hover:underline">
          View Helper Agreement
        </Link>
      </div>
    </div>
  )
}
